# WHAT IS NUMPY?

It is a fundamental open-source library in Python for scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently. 

## Key features and uses of NumPy:
* N-dimensional array object (ndarray): This is the core feature of NumPy, allowing for efficient storage and manipulation of large datasets in various dimensions (e.g., vectors, matrices, or higher-dimensional tensors).
  
* Performance: NumPy arrays are significantly faster than standard Python lists for numerical operations, primarily because they are stored contiguously in memory and are implemented in optimized C code.


* Mathematical functions: It offers a wide range of mathematical functions for array operations, including linear algebra, Fourier transforms, random number generation, statistical operations, and more.


* Integration with other libraries: NumPy forms the foundation for many other popular Python libraries used in data science and machine learning, such as Pandas, Matplotlib, SciPy, scikit-learn, TensorFlow, and PyTorch.

  
* Data science and machine learning: NumPy is essential for tasks involving numerical data manipulation, analysis, and the implementation of algorithms in fields like data science, machine learning, and scientific research.



In essence, NumPy provides the essential tools for high-performance numerical computation in Python, making it an indispensable library for anyone working with numerical data in the language.

## What are we going to cover?

* Most useful functions
* NumPy datatypes & attributes (ndarray)
* Creating arrays
* Viewing arrays & matrices
* Manipulating & compariing arrays
* Sorting arrays
* Use cases

In [1]:
## First we have to import numpy

import numpy as np

## 1. Datatypes and Attributes 

In [2]:
## Numpy main datatype is ndarray i.e. n-dimensional array

a1 = np.array([1,2,3])
a1


array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.3,3.3],[4.5,5,6.7]])

a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

a2

array([[1. , 2.3, 3.3],
       [4.5, 5. , 6.7]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
## Attribute associated with numpy

a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
## to check the no of dimmenction

a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
## to check teh data type 

a1.dtype, a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
## to check the size of the array

a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
## Create a DataFrame from a Numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.3  3.3
1  4.5  5.0  6.7

## 2. Creating Arrays 

In [13]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [14]:
''' 
So here what is happing is that , whenever you write a function and within the brackets
you press shift + tab , it will show what that fuction do and what it will return .
'''
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

## So what it has done that , it put the 1's in the given shape i.e 2 rows and 3 columns by defalut

In [16]:
ones.dtype

dtype('float64')

In [17]:
## this can be done with zeros as well, we can create the nd with 1 or 0
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[0, 5, 2, 2, 4],
       [4, 4, 2, 3, 3],
       [9, 0, 6, 7, 5]], dtype=int32)

In [20]:
''' 
As we have seen , numpy generate random numbers but ther are not random 
numbers, there are pseudo random numbers. To conferm there are pseudo random 
numbers, we can use "np.random.seed()" this line .
'''

## lets take an example
random_array_1 = np.random.randint(10,size=(5,3))
random_array_1

array([[5, 2, 8],
       [7, 2, 1],
       [6, 7, 1],
       [7, 6, 6],
       [9, 0, 3]], dtype=int32)

In [21]:
'''
So what we want now is that , when we send this file to anyone,
for testing or to run the file, we have don't need to send the 
same numbers. so to avoid that , we use Pseudo - random numbers.

It allows not to generate new random numbers as many time we run the code.

'''
np.random.seed(seed=0) ## seed value can be any number
random_array_2 = np.random.randint(10,size=(5,3))
random_array_2

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

## 3. Viewing Arrays and Matrices

In [22]:
## How to find the unique number in array 

np.unique(random_array_2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [23]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
a3[:2 ,:2, :2]
## This will give you 2 rows , two columns and there respective values

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [31]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

## 2 ---> It notes the pair, here it is a pair of 3 matrices.
## 3 ---> It represnet in one pair , how many matrices are there, here it is 3.
## 4 ---> It denotes the no of rows in a matrice.
## 5 ---> It represent the no of columns in a matrice.


array([[[[5, 7, 3, 6, 6],
         [7, 9, 1, 9, 6],
         [0, 3, 8, 4, 1],
         [4, 5, 0, 3, 1]],

        [[4, 4, 4, 0, 0],
         [8, 4, 6, 9, 3],
         [3, 2, 1, 2, 1],
         [3, 4, 1, 1, 0]],

        [[7, 8, 4, 3, 5],
         [6, 3, 2, 9, 8],
         [1, 4, 0, 8, 3],
         [9, 5, 5, 1, 7]]],


       [[[8, 6, 4, 7, 3],
         [5, 3, 6, 4, 7],
         [3, 0, 5, 9, 3],
         [7, 5, 5, 8, 0]],

        [[8, 3, 6, 9, 3],
         [2, 7, 0, 3, 0],
         [3, 6, 1, 9, 2],
         [9, 4, 9, 1, 3]],

        [[2, 4, 9, 7, 4],
         [9, 4, 1, 2, 7],
         [2, 3, 9, 7, 6],
         [6, 2, 3, 6, 0]]]], dtype=int32)

In [32]:
a4.size , a4.shape, a4.ndim

(120, (2, 3, 4, 5), 4)

In [33]:
## Lets see how we can get the 1st 4 elements of the inner most array
### We have to use slicing method. 
## To get the first 4 elements , we have to slice
## 1. all of dimmention 1,2,3 but only after the 4 numbers

a4[: ,: ,: ,:4]
## Here you can see we get only 4 numbers . This last value can be anynumber.

array([[[[5, 7, 3, 6],
         [7, 9, 1, 9],
         [0, 3, 8, 4],
         [4, 5, 0, 3]],

        [[4, 4, 4, 0],
         [8, 4, 6, 9],
         [3, 2, 1, 2],
         [3, 4, 1, 1]],

        [[7, 8, 4, 3],
         [6, 3, 2, 9],
         [1, 4, 0, 8],
         [9, 5, 5, 1]]],


       [[[8, 6, 4, 7],
         [5, 3, 6, 4],
         [3, 0, 5, 9],
         [7, 5, 5, 8]],

        [[8, 3, 6, 9],
         [2, 7, 0, 3],
         [3, 6, 1, 9],
         [9, 4, 9, 1]],

        [[2, 4, 9, 7],
         [9, 4, 1, 2],
         [2, 3, 9, 7],
         [6, 2, 3, 6]]]], dtype=int32)

In [34]:
a4[: ,: ,: ,:2]

array([[[[5, 7],
         [7, 9],
         [0, 3],
         [4, 5]],

        [[4, 4],
         [8, 4],
         [3, 2],
         [3, 4]],

        [[7, 8],
         [6, 3],
         [1, 4],
         [9, 5]]],


       [[[8, 6],
         [5, 3],
         [3, 0],
         [7, 5]],

        [[8, 3],
         [2, 7],
         [3, 6],
         [9, 4]],

        [[2, 4],
         [9, 4],
         [2, 3],
         [6, 2]]]], dtype=int32)

In [35]:
a4[: ,: ,: ,:1]

array([[[[5],
         [7],
         [0],
         [4]],

        [[4],
         [8],
         [3],
         [3]],

        [[7],
         [6],
         [1],
         [9]]],


       [[[8],
         [5],
         [3],
         [7]],

        [[8],
         [2],
         [3],
         [9]],

        [[2],
         [9],
         [2],
         [6]]]], dtype=int32)

 ## 4. Manipulating and Comparing Arrays

### Arithmetic 

In [36]:
a1

array([1, 2, 3])

In [37]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
## Additions
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [40]:
## Subtractions 

a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [41]:
## Multipications

a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [42]:
a2 * a1

array([[ 1. ,  4.6,  9.9],
       [ 4.5, 10. , 20.1]])

In [43]:
## How can you reshape a2 to be compaatible with a3 ?
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [44]:
## as you can see it showing error , so to match the shape we can use a 
#3 function called reshape

a2_reshaped = a2.reshape(2, 3, 1)
a2_reshaped * a3

array([[[  1. ,   2. ,   3. ],
        [  9.2,  11.5,  13.8],
        [ 23.1,  26.4,  29.7]],

       [[ 45. ,  49.5,  54. ],
        [ 65. ,  70. ,  75. ],
        [107.2, 113.9, 120.6]]])

In [47]:
## Divisons
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [48]:
## Floor divisions removes the decimals 
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [49]:
## Power 
a2 ** 2

array([[ 1.  ,  5.29, 10.89],
       [20.25, 25.  , 44.89]])

In [51]:
## Modulos
a2 % 2

array([[1. , 0.3, 1.3],
       [0.5, 1. , 0.7]])

In [52]:
## exponetion
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [53]:
## log
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregations

It is performing the same operation on a number of thing which is nupy arrays.

In [54]:
listy_list = [1,2,3]
type(listy_list)

list

In [55]:
sum(listy_list)

6

 Use python's methods on python dataframe (sum()) and use 
 Numpy's methods on Numpy arrays (np.sum())

In [57]:
## Create a massive numpy arrays

massive_array = np.random.random(100000)
massive_array.size

100000

In [58]:
massive_array[:10]

array([0.02706898, 0.73139734, 0.76696351, 0.00976644, 0.30828617,
       0.23286547, 0.50342743, 0.95372138, 0.5578113 , 0.09746869])

In [59]:
## % this will show how much time it will take to run every line of code

%timeit sum(massive_array)  # Pyhton's sum()
%timeit np.sum(massive_array) # Numpy's sum()

6.05 ms ± 22.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
27.3 μs ± 1.57 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [62]:
''' 
So as you can see that , numpys functions are much faster then the pythons funtions.
So always use numpy functions for solving any mathmetical questions.
'''

' \nSo as you can see that , numpys functions are much faster then the pythons funtions.\nSo always use numpy functions for solving any mathmetical questions.\n'

In [61]:
np.mean(a2)

np.float64(3.8000000000000003)

In [63]:
np.max(a2), np.min(a2), np.std(a2), np.var(a2)

(np.float64(6.7),
 np.float64(1.0),
 np.float64(1.8565200420859096),
 np.float64(3.446666666666667))

## Dot Product

In [64]:
np.random.seed(0)

mat1= np.random.randint(10, size=(5,3))
mat2= np.random.randint(10, size=(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [65]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [66]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [67]:
np.dot(mat1 , mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [68]:
'''
So as you can see that the dot product cannot be perfromed . The reason is that 
* The number on the inside muct match . i.e -> 3x(3) -----> (3)X2, so that it can give 
the output of 3x2 which is outside number.

But here you can that , the inside number are the not same i.e 5x3------> 5x3.
That's why it is showing the error.
'''

"\nSo as you can see that the dot product cannot be perfromed . The reason is that \n* The number on the inside muct match . i.e -> 3x(3) -----> (3)X2, so that it can give \nthe output of 3x2 which is outside number.\n\nBut here you can that , the inside number are the not same i.e 5x3------> 5x3.\nThat's why it is showing the error.\n"

In [69]:
## So to do the dot product , we have to perform the trasnpose of any one matrice
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]], dtype=int32)

In [71]:
mat1.T.shape

(3, 5)

So you can see that the order / shape of the matric is changed, so now we can 
perfrom the dot product operation.

In [73]:
mat3 = np.dot(mat1,mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [74]:
mat3.shape

(5, 5)

## 5. Sorting Arrays

In [75]:
random_array

array([[0, 5, 2, 2, 4],
       [4, 4, 2, 3, 3],
       [9, 0, 6, 7, 5]], dtype=int32)

In [76]:
np.sort(random_array)

array([[0, 2, 2, 4, 5],
       [2, 3, 3, 4, 4],
       [0, 5, 6, 7, 9]], dtype=int32)

In [78]:
np.argsort(random_array) ## It will short the indexes

array([[0, 2, 3, 4, 1],
       [2, 3, 4, 1, 0],
       [1, 4, 2, 3, 0]])

In [80]:
np.argmin(random_array), np.argmax(random_array)

(np.int64(0), np.int64(10))